# Generated by Django 4.2.4 on 2023-09-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfile',
            old_name='lead',
            new_name='client',
        ),
    ]
